### ISSUE TITLE
New lines around a property outputs [object Object] rather than the html

### ISSUE THREAD

**Issue by jonashagstedt** [wix/react-templates#10]
<ul class="children">{this.props.children}</ul>

    
    <ul class="children">
        {this.props.children}
    </ul>

(other than React templates are great!)

**Comment by avi** [comment]
Fixed... and added a test so it won't break in the future.
Will publish in a couple of days

**Comment by jonashagstedt** [comment]
Nice one.

I'll give it a go as soon as it's pushed.

Cheers

**Comment by damianmr** [comment]
Ah, thanks, I got into this problem and thought that using {this.props.children} was something ReactTemplates didn't support
