### ISSUE TITLE
add support for rt-include

### ISSUE THREAD

**Issue by idok** [wix/react-templates#100]
add rt-include, a macro that takes a text (svg/html/more?) file and injects it into the file as if it was part of the original markup

a.rt
```html
<div>
  <rt-include src="./my-icon.svg" />
</div>
```

my-icon.svg
```html
  <svg xmlns="http://www.w3.org/2000/svg">
      <rect height="50" width="50" style="fill: #00f"/>
  </svg>
```

is equivalent to

```html
<div>
  <svg xmlns="http://www.w3.org/2000/svg">
      <rect height="50" width="50" style="fill: #00f"/>
  </svg>
</div>
```

**Comment by nippur72** [comment]
The playground must handle it as a special case.

**Comment by avi** [comment]
pushed, but didn't add support for playground, as the only interesting case in the playground is for supporting urls and I don't think it is currently worth the effort of refactoring everything to be async.
