### ISSUE TITLE
autofocus not working

### ISSUE THREAD

**Issue by steezeburger** [wix/react-templates#102]
Adding the autofocus attribute to an input tag is not working as far as I know. Anyone else had this issue or know how I can get around it? I've tried calling focus like so in `componentDidMount` but for some reason my `this.refs` object is empty so it does not work: 
```
  ReactDOM.findDOMNode(this.refs.nameInput).focus(); 
```
 Any ideas?

**Comment by nippur72** [comment]
The `autoFocus` attributes does work (I've just checked), don't forget to spell it in *camelCase*.

**Comment by steezeburger** [comment]
I had tried that and it still didn't seem to work. I'll keep digging around and try to see where the issue lays.
