### ISSUE TITLE
rt-class doesn't work with lodash 4.5.0

### ISSUE THREAD

**Issue by shaylh** [wix/react-templates#105]
Looks like lodash's implementation of "_.pick" changed in 4.5.0, and now 

`_.pick({ foo: true }, _.identity)`

returns an empty object.

[Codepen example with lodash 3.10.0](http://codepen.io/anon/pen/wMbLzm)
[Codepen example with lodash 4.5.0](http://codepen.io/anon/pen/jWojre)

:)

**Comment by nippur72** [comment]
don't know how `pick` is used in `rt`, but perhaps it's enough to replace it with `pickBy`  ?

[Codepen with _.pickBy](http://codepen.io/anon/pen/qbeOyb)

**Comment by shaylh** [comment]
Unfortunately no, because _.pickBy was only introduced in lodash 4.5.0.

**Comment by nippur72** [comment]
I mean, is the new `pickBy` equivalent to the old `pick` ? If so, at we could a switch or something like that.

**Comment by nippur72** [comment]
any ideas about how to solve this issue? Today I spent a long time debugging why my classes weren't working ...

**Comment by shaylh** [comment]
`_({foo: true, bar: false}).transform(function(res, value, key){
    if(value){
        res.push(key);
    }
}, []).value().join(' ');`

A bit ugly, I guess it could be improved, though it does the work on both lodash versions :)

**Comment by sergio11** [comment]
I have the same problem. Could you close the issue? please :)

**Comment by shaylh** [comment]
@mariawix , can you please also update the NPM repository? :)
