### ISSUE TITLE
Auto bind event handler option

### ISSUE THREAD

**Issue by airtoxin** [wix/react-templates#109]
I got those error many times... `RTCodeError: when using 'on' events, use lambda '(p1,p2)=>body' notation or use {} to return a callback function. error: [onClick='this.onClick']`

Is there any option of auto bind event handler function?

**Comment by nippur72** [comment]
that would be a nice feature to have.

I've solved this with a post-processing tool of my own that binds to `this` if the on-event attribute starts with `this.`.

**Comment by nippur72** [comment]
here is an article that describes how people currently handle binding (out of react-templates): [react-binding-patterns-5-approaches-for-handling-this](https://medium.com/@housecor/react-binding-patterns-5-approaches-for-handling-this-92c651b5af56#.ht64ifkd8)
