### ISSUE TITLE
fix react/addons require for react 15

### ISSUE THREAD

**Issue by G3z** [wix/react-templates#116]
in react 15.0.0 `react/addons` is not a valid entry point any more as stated [here](https://facebook.github.io/react/blog/#removed-deprecations)

generated code like
```javascript
'use strict';
var React = require('react/addons');
var _ = require('lodash');
var myComp = require('comps/myComp');
var utils = require('utils/utils');
module.exports = function () {
    return React.createElement('div', {}, React.createElement(myComp, { 'customProp': utils.doSomething() }, 'myComp is just a regular tag'));
};
```
is no longer working with react 15.0.0

**Comment by nippur72** [comment]
until `15.0.0` is added to react-templates, you should continue to target `0.14.0` so that the correct `require` is generated.

**Comment by ssserg** [comment]
Any news on when the new version is going to be added?

**Comment by rileylnapier** [comment]
id love news on this too.  this information should be in the readme at top
