### ISSUE TITLE
item index in rt-repeat

### ISSUE THREAD

**Issue by t1m0n** [wix/react-templates#121]
Hello, is where any way to get index of item in `rt-repeat`? e.g.

````html
<div rt-repeat="item in this.state.items">
     <span>Item index is {item.index} or {item._index}</span>
</div>
````
It would be useful for `key` attribute if items have no ids. 

I know that I can get index this way:

````html
<div rt-repeat="item in this.state.items" rt-scope="this.state.items.indexOf(item) as index">
     <span>Item index is {index}</span>
</div>
````
But I think it would be great if we could be able to get `index` automatically, what do you think?

 Thanks.

**Comment by nippur72** [comment]
if you have `item` in a repeat, then a variable named `itemIndex` will be automatically put in the scope.

**Comment by t1m0n** [comment]
@nippur72 Oh thanks, didn't read docs carefully, my bad.
