### ISSUE TITLE
problems with module es6

### ISSUE THREAD

**Issue by chrvadala** [wix/react-templates#122]
Hi,
I want to use React Template with es6.

I have this simple file that I want to convert thought React Template
`<div>Hello</div>`

but if I run `./node_modules/.bin/rt -m es6 hello.rt` the build doesn't work and give me this output
`error  this[stmt.type] is not a function`

What am I doing wrong?

**Comment by ganimomer** [comment]
Hi,
I tried doing the exact same thing you did and it worked as expected.

Could you try again with the latest version (released today)?

**Comment by chrvadala** [comment]
I have found the cause of the problem. I'm using react-templatify, the suggested browserify extension and I have found that this extension force npm to install an older version of react-templates https://github.com/gja/react-templatify/blob/master/package.json#L8
Now it works. 
Thank you for your support!
