### ISSUE TITLE
Is there possibility output file to be exactly es6 code and not transpiled es5 closure (like in babel)?

### ISSUE THREAD

**Issue by idchlife** [wix/react-templates#127]

**Comment by nippur72** [comment]
I'm not sure to understand what you mean, the output from react-templates is basically a `function() {}`, so it's the same in es5 and es6. Can you make an example of what would be your desidered output?

**Comment by idchlife** [comment]
@nippur72 the thing is I actually misunderstood purpose of react-templates. I thought it was about creating automatically classes with render methods and stuff, where you then will write methods which are mentioned in templates etc.
Right now I'm at the point where I need to do some html-css stuff for react app. So I thought output will be exactly copy of react-templates but react components.

Somehow I did not get at first glance that this simply transforms html templates to jsx and helps you to import them and use as return template in render.
