### ISSUE TITLE
Embedding React Code should not lead to string concatenation

### ISSUE THREAD

**Issue by gja** [wix/react-templates#13]
I have the following in my template
```html
<div class="foobar">
  {React.createElement("h1", {}, "Hello, World!")}
</div>
```

Obviously, I have something a bit more complex than just creating a simple element (it calls this.createMyElement(someDataIGetInALoop).

However, this compiles as follows:
```js
React.createElement("div", {}, "\n   " + React.createElement("h1", {}, "Hello, World!") + "\n")
```

which always gives you the output [Object Object].

I thought of one of two ways to potentially solve this.
1) Either get rid of spacing around {}
2) Create a new field called rt-content, which will let you set the children programatically.

**Comment by damianmr** [comment]
I also need something like this. In particular, my use case is to print children of a node. Something like

```
<div class="my-wrap">
   {this.props.children}
</div>
```

So that I can use it like this:

```
<MyWrap>
    <h1>I will be wrapped</h1>
</MyWrap>
```

Is there any way to achieve this?

**Comment by damianmr** [comment]
Sorry I didn't see this issue (aparently fixed):
https://github.com/wix/react-templates/issues/10

Is this fixed in the latest published version? Thanks!
