### ISSUE TITLE
[Help needed] surjective & non-bijective functions drawing

### ISSUE THREAD

**Issue by Pinxie** [wix/react-templates#133]
Hello,

I can have curves which possess 2 Y values for the same X. for example :

![plotnoninjective](https://cloud.githubusercontent.com/assets/15984761/15328718/1cce4ba6-1c56-11e6-8cfe-17ae4c5ddbff.png)

Is it at all possible to do this kind of thing with react-stockcharts, and if not, is there for me any way to do it without breaking everything?  I didn't upgrade react-stockcharts yet since last time ( 6 months ago...), is the fact that _data_ must be sorted by X still a prerequisite?

**Comment by nippur72** [comment]
How is this related to `react-templates` ?

**Comment by Pinxie** [comment]
Woops wrong repository, sorry completely unrelated
