### ISSUE TITLE
Vendor prefixes aren't parsed as the react documentation recommends

### ISSUE THREAD

**Issue by Purii** [wix/react-templates#144]
## Description

Using a vendor prefix within a style tag results in a warning of react:

> Warning: Unsupported vendor-prefixed style property mozHyphens. Did you mean MozHyphens? Check the render method of `StatelessComponent`.

HTML-Element:

```
<div rt-stateless>
<span style="-moz-hyphens:auto;-webkit-hyphens:auto;hyphens:auto;line-height:20px;margin:0;padding:0;text-align:left;vertical-align:top;word-wrap:break-word">Example</span>
</div>
```

According to the docs of react, vendor prefixes `should begin with a capital letter.` (https://facebook.github.io/react/tips/inline-styles.html)

---
## Dependencies
- react-templates: 0.5.2
- react: 15.1.0

**Comment by nippur72** [comment]
I don't understand... you are using a lowercase prefix and React is putting a warning as per documentation. Why should this be an issue?

**Comment by Purii** [comment]
Usually I write `CSS` in lowercase. It would be great, if `React Templates` would output `react`-compatible JavaScript-styles, no matter how the input is formatted.

**Comment by nippur72** [comment]
Ok, now I get what you mean, you want it to parse `style` attributes and pass them to react. I guess the same could be said for event handlers (`onclick` vs `onClick`). 

Currently `react-templates` does not parse anything, but I understand your point of writing CSS (and HTML in general) the way it's supposed to be (with advantage of intellisense etc etc).

**Comment by nippur72** [comment]
Well, actually this turns to be a bug, because you can't specify an uppercase starting letter even if it's legit.

Currently,
```html
<span style="-Moz-hyphens:auto">Example</span>
```
is wrongly turned into:
```js
var templateRT = function () {
    return React.createElement('span', { 'style': { mozHyphens: 'auto' } }, 'Example');
};
```
(notice the lowercase `mozHyphens`)

So definitely something to be fixed.

**Comment by Purii** [comment]
Seems that `handleStyleProp` is the relevant function. (https://github.com/wix/react-templates/blob/ff5bccdd93e81cbabf4d1837d98de16de0615174/src/reactTemplates.js#L221)

**Comment by nippur72** [comment]
I'm just fixing it

**Comment by nippur72** [comment]
Ok, I've submitted a PR for this. Vendor prefixes taken into consideration are: `moz`, `o`, `webkit` and `ms` no matter what case you use, it's always correct.

**Comment by Purii** [comment]
Thanks! 👍
