### ISSUE TITLE
how to set 'native' option to true?

### ISSUE THREAD

**Issue by PierBover** [wix/react-templates#165]
The [docs](https://github.com/wix/react-templates/blob/gh-pages/docs/native.md) for using `react-templates` with `react-native` specify that:

> In order to use React Templates for React Native you should set the native option to true.

Where is this option set?

**Comment by nippur72** [comment]
by looking at the source, it's `--native`.

**Comment by PierBover** [comment]
Thanks again @nippur72 

Can you post a link to the source?

How would I use that option which looks like a shell command option?

**Comment by PierBover** [comment]
So I figured out this `--native` argument has to be used with the [CLI](https://github.com/wix/react-templates/blob/gh-pages/docs/cli.md) although when compiling the following template with `rt test.rt --native`:

```
<View>
    <ListView dataSource="{this.state.dataSource}">
        <Row>
            <Text>{rowData}</Text>
        </Row>
    </ListView>
</View>
```

I get:

```
var testRT = function () {
    return React.createElement(View, {}, React.createElement(ListView, { 'dataSource': this.state.dataSource }, React.createElement(Row, {}, React.createElement(Text, {}, rowData))));
};
```

instead of  what [the docs suggest](https://github.com/wix/react-templates/blob/gh-pages/docs/native.md) I should get:

```
'use strict';
var React = require('react-native');
var _ = require('lodash');
function renderRow1(rowData) {
    return React.createElement(React.Text, {}, rowData);
}
module.exports = function () {
    return React.createElement(React.View, {}, React.createElement(React.ListView, {
        'dataSource': this.state.dataSource,
        'renderRow': renderRow1.bind(this)
    }));
};
```

**Comment by PierBover** [comment]
My bad, I wasn't using the '-r' to overwrite the previous file.

Now I get:

```
var testRT = function () {
    function renderRow1(rowData, sectionID, rowID, highlightRow) {
        return React.createElement(React.Text, {}, rowData);
    }
    return React.createElement(React.View, {}, React.createElement(React.ListView, {
        'dataSource': this.state.dataSource,
        'renderRow': renderRow1.bind(this)
    }));
};
```

But this still lacks the `var React = require('react-native')`.

**Comment by PierBover** [comment]
I will be closing this now since the original question has been solved.

**Comment by nippur72** [comment]
You have to provide the `--modules commonjs` option too, otherwise it will default to `none` (no modules).

> Can you post a link to the source?

see [options.js](https://github.com/wix/react-templates/blob/gh-pages/src/options.js)

**Comment by PierBover** [comment]
Strange. The [docs](https://github.com/wix/react-templates/blob/gh-pages/docs/native.md) say:

> In native mode the default modules option is set to commonjs and the default react-import-path is set to react-native.

Maybe I'm doing something wrong.

When using `rt template.rt -r --modules commonjs --native` I get:

```js
'use strict';
var React = require('react/addons');
var _ = require('lodash');
module.exports = function () {
    return React.createElement(React.View, {}, React.createElement(React.Text, {}, 'Hola'));
};
```

Which still misses `var React = require('react-native');`.

**Comment by PierBover** [comment]
It seems I got it right with `rt template.rt -r --modules commonjs --native --react-import-path react-native`.

I will open a new bug about the `--native` option not doing its thing.
