### ISSUE TITLE
Compile template syntax in jsx files

### ISSUE THREAD

**Issue by Prestaul** [wix/react-templates#17]
It would be nice if this template markup syntax, with sugar for looping/conditionals/etc, could be used in a component `.jsx` file as well as in a `.rt` file.

Many people do prefer their markup in their component, but would still benefit from all the syntactic sugar added by react-templates. How hard would it be to extend the compiler to be able to process a full `.jsx` file?

**Comment by enricribas** [comment]
+1 Personally, these two things belong together, why do I want them in two files. maybe a 

```html
<template>
   template here inside the JSX file itself.
</template>
```

similar to the way Polymer does it.

**Comment by avi** [comment]
Mixing ReactTemplates and JSX seems wrong... but we can add support for JavaScript with templates in it, so the view and the code can co-exist (jsrt instead of jsx)

**Comment by FelikZ** [comment]
@idok is it implemented?

**Comment by Prestaul** [comment]
@idok, I think we're wondering if this closure indicates "request denied" or that you think the issue has been addressed.

The issue being: 
> Many people do prefer their markup in their component, but would still benefit from all the syntactic sugar added by react-templates.

**Comment by ganimomer** [comment]
The request has been implemented but not documented. Sorry about that.
We've added it to end of the README.

**Comment by Prestaul** [comment]
:+1: & :pineapple:

**Comment by FelikZ** [comment]
@ganimomer you've made my day, thanks.
