### ISSUE TITLE
conditional props

### ISSUE THREAD

**Issue by PierBover** [wix/react-templates#173]
I'm trying to figure out how to pass conditional props using `rt-props` but I'm getting the error `RTCodeError: Unexpected token .`.

The docs say:

> The expected value of this attribute is an expression returning an object.

So I tried:

```html
<div rt-props="{this.state.isEditing ? {selected:this.state.something.id} : {}}">

// also just in case
<div rt-props="{this.state.isEditing ? {selected:this.state.something.id} : null}">
<div rt-props="{this.state.isEditing ? {selected:{this.state.something.id}} : {}">
```

Is it possible to use a ternary expression in `rt-props`? What is the correct form?

**Comment by nippur72** [comment]
special attributes like `rt-props` and `rt-if` don't need to be escaped with `{` and `}` because it's known that their argument is a javascript expression. So it's just

```html
<div rt-props="this.state.isEditing ? {selected:this.state.something.id} : {}" >
```

**Comment by PierBover** [comment]
Oh right, so of course if I escape this is a malformed object.

Thanks @nippur72 !
