### ISSUE TITLE
props variable is not available in stateless templates

### ISSUE THREAD

**Issue by delijah** [wix/react-templates#182]
In a lot of cases props is not available, which is sad because i really like and would like to use the stateless feature. On the root level it's there but it is not available...

- within event handlers using lambda notation
- within rt-repeat
- probably in other places

I am using react-templates 0.5.2.

**Comment by nippur72** [comment]
the [bugfix](https://github.com/wix/react-templates/pull/142) has been merged into master (`gh-pages`), but a new version has not been released yet.

If you want to use the feature, you can still install it from the GitHub repo:

```
npm uninstall react-templates -g
npm install -g git://github.com/wix/react-templates.git#gh-pages 
```

**Comment by delijah** [comment]
Awesome, thank you! So i will close this issue.
