### ISSUE TITLE
Cannot find module when using rt-import

### ISSUE THREAD

**Issue by davenlin19** [wix/react-templates#187]
Hello,

I'd like to import a template in another template but it didn't work:

Header.rt:
`<rt-import name="Presentation" from="./Presentation" />`
`<Presentation></Presentation>`

I'm pretty sure that i have `Presentation.jsx` and `Presentation.rt` in the same folder with `Header.rt` but i still have this error:

`Cannot find module: './Presentation'`

Thank you in advance !

**Comment by nippur72** [comment]
Assuming you are using commonjs modules, `react-templates` exports the render function "as a whole", e.g.:
```js
module.exports = function ...;
```
that means you cannot import them with `name="Presentation"`, but you have to use:
```HTML
<rt-import name="*" as="Presentation" from="./Presentation" />
```
this seems somewhat counterintuitive, but it mimics the ES6 import syntax:
```js
import * as Presentation from "./Presentation";
```
You can also use the old `rt-require`:
```HTML
<rt-require dependency="./Presentation" as="Presentation" />
```

**Comment by davenlin19** [comment]
Thanks for your answer. I tried to use 

`<rt-import name="*" as="Presentation" from="./Presentation" />`

and change the extension of this file `Presentation.jsx` to `Presentation.js` so i don't have any problem with the compilation.

But i still cannot use `<Presentation></Presentation>` in the `Header.rt` file. My page becomes blank and there are some errors in the browser's console:

`warning.js:36 Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of 'Header'.`

`invariant.js:38 Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `Header`.`

Do you know how to fix it ? Thank you !

**Comment by nippur72** [comment]
If you have this:
```html
<rt-import name="*" as="Presentation" from="./Presentation" />
<Presentation></Presentation>
```
then `Presentation` can be one of the following:
1. a stateless react component made directly from a `.rt` template using the `rt-stateless` attribute.
2. a stateful react component, made from a `.js` file and `.rt`

Examples:
Case 1: stateless component using only react-templates:
```html
<!-- presentation.rt -->
<div rt-stateless>I am presentation</div>
```

Case 2: stateful component
```html
<!-- presentation-template.rt -->
<div>I am presentation</div>
```
```js
// presentation.js -->
import { React } from "react";
class Presentation extends React.Component { }
Presentation.prototype.render = require('presentation-template');
module.exports = Presentation;
```

**Comment by davenlin19** [comment]
Thank you very much. You save my life !

Yes, my `Presentation` is stateful. I think i don't quite understand why but in my `Presentation.js`, i changed from 

`export default class Presentation extends React.Component` 

to

`class Presentation extends React.Component`
`...`
`module.exports = Presentation`

and it works.

**Comment by steezeburger** [comment]
This is happening to me too but only when using `rt-import` in a nested component. I have a components directory in an index.js that exports all my components as named exports. This works great everywhere, and I don't get an error about a file not existing or anything, it just isn't a proper React component.

**Comment by nippur72** [comment]
@steezeburger can you post an example of what is not working? I'm sure it's only a matter of the way things are exported.

**Comment by steezeburger** [comment]
I figured out this was an error with react-templates-loader, modules type, and import/export. I had an index.js in my component directory that exported all components. I had webpack set up with a root resolve so that I could use `from="component"` in my rt-imports. This worked fine until I tried using that convention in a nested component (container > one level deep component (works) > two level deep (doesn't work)). It worked using `name="default"` and specifying the relative path however. I tried changing modules to es6 and began getting other, different errors about import being an unexpected token.

We actually got a new developer recently which allowed us to drop our dependency on our designer writing markup, so we've since moved away from react templates however, so this is no longer an issue.

**Comment by kelsonic** [comment]
> Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of 'App'.
> 
> Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of App.

I get the same error as @davenlin19 and the suggested fixes did not work.

**App Component**
```
import React, { Component } from 'react';
import { connect } from 'react-redux';
import selectAppDetails from './selectors';
import view from './view.rt';

class App extends Component {
}

App.prototype.render = view;

const mapStateToProps = selectAppDetails();

function mapDispatchToProps(dispatch) {
  return {
    dispatch,
  };
}

export default connect(mapStateToProps, mapDispatchToProps)(App);
```

**App view.rt**
```
<rt-import name="*" as="SomeComponent" from="../../containers/SomeComponent" />
<div>
  <SomeComponent />
</div>
```

**SomeComponent**
```
import React, { PureComponent } from 'react';

class SomeComponent extends PureComponent {
}

Address.prototype.render = view;

export default SomeComponent;
```

**SomeComponent view.rt**
```
<div>
  Copyright
</div>
```

Any suggestions?

**Comment by nippur72** [comment]
in `SomeComponent`, what are `Address` and `view` (e.g. where you define them?)

**Comment by kelsonic** [comment]
@nippur72 Sorry, that was bad pasting on my part. I edited my comment.

**Comment by nippur72** [comment]
SomeComponent is exported as default but later imported as "*". You need to be consistent between import/export.

**Comment by kelsonic** [comment]
I get the same error when I import it as such:
`<rt-import name="default" as="SomeComponent" from="../../components/SomeComponent" />`

**Comment by kelsonic** [comment]
I found the solution:

**SomeComponent**
```JSX
import React, { PureComponent } from 'react';
import view from './view.rt';

class SomeComponent extends PureComponent {
}

SomeComponent.prototype.render = view;

module.exports = SomeComponent;
```
instead of using `export default SomeComponent`.

I am using `<rt-import name="default" as="SomeComponent" from="../../components/SomeComponent" />` as you suggested @nippur72. 

Thanks for the help! :)
