### ISSUE TITLE
Linting for react-templates

### ISSUE THREAD

**Issue by delijah** [wix/react-templates#189]
I am missing a linting possibility for react-templates. There is a quite nice linting plugin for JSX. Would be awesome to have this feature for react-templates!

https://github.com/yannickcr/eslint-plugin-react

**Comment by nippur72** [comment]
For a linter to be realized we need to improve how `react-templates` parses and generates the code. Currently, it's not the canonical text file -> AST -> code, in other words we don't have an AST for the linter to reason about.

**Comment by delijah** [comment]
Thank you very much for your answer. One of the reasons i've switched to JSX, even though i love the idea of react-templates!
