### ISSUE TITLE
Template Inheritance; this.props is undefined

### ISSUE THREAD

**Issue by bencripps** [wix/react-templates#195]
This is my main template

````js
<rt-import name="default" as="Header" from="./../component/shared/header/index.rt"/>
<div>
   <Header />
   {  this.props.children }
</div>
````

And the secondary Template that uses it:

````js
<rt-import name="default" as="Main" from="./main.rt"/>
<Main>
  <span>This is a secondary page</span>
</Main>
````

If I remove the `this.props.children` from the `main.rt` this document loads. How can I nest my components, and why is `this.props` undefined here?

**Comment by bencripps** [comment]
At the template scope `this` is an empty object.

**Comment by nippur72** [comment]
you cant import main from main.rt because it does not contain the whole component but only the render function. You might turn main into a stateless component (and drop the "this" from "this.props.children").

**Comment by bencripps** [comment]
Yup, that was it! Thanks!
