### ISSUE TITLE
API For RT

### ISSUE THREAD

**Issue by jmc420** [wix/react-templates#213]
Hi

Is there an API which allows you to run the rt compiler within a program (either in nodejs or in a browser); I guess in nodejs one could fork a task but as I guess the playground runs within a browser environment?

James

**Comment by nippur72** [comment]
there is no formal API, but you can `require` and use the javascript modules from `node_modules/react-templates`. I do that in my (still unfinished) **rioct-cli** project, see for example [rtExtractor.ts](https://github.com/nippur72/rioct-cli/blob/master/rtExtractor.ts).

**Comment by jmc420** [comment]
thanks for that and pointing me at your project; I work in typescript so it will be very useful.
