### ISSUE TITLE
does this support "template-url" feature like angularjs?

### ISSUE THREAD

**Issue by eddyzhang1986** [wix/react-templates#227]
does this support "template-url" feature like angularjs?

**Comment by nippur72** [comment]
can you make an example?

**Comment by eddyzhang1986** [comment]
on the server side:
response a template like:
<div>{this.state.hello}</div>
on the client side:
import ...
import translate from 'react-templates';

class hello extends Component
{
   constructor(props)
   {
      super(props);
      this.state={
         renderCode:null
       }
   }
   componentDidMount
   {
         $.get("api/helloTemplate",function(template){
               this.setState({renderCode:translate(template)};
          }
    }
    render()
    {
        return {this.state.renderCode};
   }
}

**Comment by eddyzhang1986** [comment]
hi@nippur72 , I am very sorry because  I think that my idea is wrong,thanks all the same for your help.
