### ISSUE TITLE
dangerouslySetInnerHTML does not work

### ISSUE THREAD

**Issue by delijah** [wix/react-templates#24]
There is a way to render raw HTML in react, see: http://facebook.github.io/react/docs/tutorial.html

I did not get this to work in react-templates.

Am i doing something wrong or is it not implemented yet?

**Comment by amitkaufman** [comment]
You should do something like:

``` html
<div dangerouslySetInnerHTML='{{ __html: yourContent }}'/>

**Comment by delijah** [comment]
Thanks that works

**Comment by PierBover** [comment]
@amitkaufman can you explain a bit all that syntax with double `{{}}` and the `_html` thing?

**Comment by nippur72** [comment]
the outer braces are for the react-templates  syntax, the innermost are for javascript object.

**Comment by PierBover** [comment]
But [dangerouslySetInnerHTML](https://facebook.github.io/react/tips/dangerously-set-inner-html.html) doesn't seem to require an object in regular React, just a regular JS expression:

```
<div dangerouslySetInnerHTML={createMarkup()} />
```

**Comment by nippur72** [comment]
but in the example createMarkup() returns an object...

**Comment by nippur72** [comment]
but in the example createMarkup() returns an object...

**Comment by PierBover** [comment]
You are right...

:facepalm:

All nighters aren't good for the mind.
