### ISSUE TITLE
pure-render-mixin with rt-if directive - documentation.

### ISSUE THREAD

**Issue by golojads** [wix/react-templates#25]
http://facebook.github.io/react/docs/pure-render-mixin.html
"pure-render-mixin" can be used when render method is "pure".

I think you should add reminder about this to "rt-if" directive documentation, because this directive produces render that is not "pure"any more.

**Comment by yotamwix** [comment]
That depends on the condition that is evaluated in the rt-if.
If the condition is based only on props\state, the render function will remain pure.
