### ISSUE TITLE
The last space before a self closing tag is significant

### ISSUE THREAD

**Issue by gja** [wix/react-templates#26]
This has actually tripped me up more than a few times. If there is no space before the '/>', we get invalid dom, which causes elements to vanish. This especially happens if you do not quote the property properly.

example:
```html
<div>
 <img class={"foobar"}/>
</div>
```
results in
```javascript
function () {
    return React.createElement('div', {}, React.createElement('img', { 'className': 'foobar' + '/' }));
};
```

```html
<div>
 <img class={"foobar"} />
</div>
```
results in
```javascript
function () {
    return React.createElement('div', {}, React.createElement('img', { 'className': 'foobar' }));
};
```

**Comment by damianmr** [comment]
This also happened to me, took a while to figure out what was going on.

**Comment by idok** [comment]
This is because this sample is not a valid rt file.
Instead, it should be written 
```html
<div>
    <img class="{'foobar'}"/>
</div>
```
I admit it is confusing, react-templates should warn on such input.
