### ISSUE TITLE
no space allowed?

### ISSUE THREAD

**Issue by dfguo** [wix/react-templates#27]
```<div onClick={ this.hello }>Hello</div>```

got this error:

```
when using 'on' events, use lambda '(p1,p2)=>body' notation or use {} to return a callback function. error: [onClick='{']
```

while

```<div onClick={this.hello}>Hello</div>```

is fine

**Comment by idok** [comment]
This is due to the parser we use, react templates is html based, which means that attributes should be surrounded with quotes, like this:
```html
<div onClick="{ this.hello }">Hello</div>
```

**Comment by dfguo** [comment]
makes sense! thanks!
