### ISSUE TITLE
Possible to use with native map function (instead of Lodash?)

### ISSUE THREAD

**Issue by jimmydivvy** [wix/react-templates#28]
I really like the syntax of react-templates, however one potential gotcha is that we're using custom container types in a few places. 

We've implemented a custom `map` function that handles these correctly, however since react-templates uses lodash for iteration it'll just treat our containers as a raw object instead of mapping correctly. 

Is there a way to toggle react-templates to call `xs.map(fn)` instead of `_.map(xs, fn)`?

**Comment by EtaiG** [comment]
_.map works on collections, not just arrays.
JS arrays have array.map but objects do not.

I don't think I understand your use case- what is your container? Is it something that inherits from an array? Why do you need a new collection type which iterates differently?

Can you post a small example?

**Comment by jimmydivvy** [comment]
As a simple example, Immutable.JS and Mori are custom collection types. In our case, we're using a combination of Immutable.JS, as well as a custom Cursor implementation that wraps underlying collections and still needs to act as a functor.

Essentially `map` needs to polymorphic and work with any Functor, rather than just JS primitives.

Adding an option to skip lodash and call `xs.map(fn)` directly instead of `_.map( xs, fn )` would be all that's required.

**Comment by dfguo** [comment]
+1

**Comment by brodybits** [comment]
Nice idea but I discovered a few other lodash dependencies:  `_.assign` and `_.keys` in the templates generated by src/reactTemplates.js; also  `_.merge` in the compiled code for a sample for `rt-props` with `_.merge` in the readme.

**Comment by brodybits** [comment]
>  I discovered a few other lodash dependencies: `_.assign` and `_.keys` in the templates generated by src/reactTemplates.js (and in some samples in http://wix.github.io/react-templates/fiddle.html); also `_.merge`

Another thing is that in terms of lodash dependencies, I only find `_.map` in test/data/*.js. It appears to me that not all possible cases are covered by the test suite.

**Comment by idok** [comment]
see my answer to #40
