### ISSUE TITLE
Don't accept nodejs PATH

### ISSUE THREAD

**Issue by LOQUILLO** [wix/react-templates#30]
![error_rt](https://cloud.githubusercontent.com/assets/1308190/7014694/be53c58c-dc8d-11e4-9909-228e35aa0ee6.png)
Don't accept the default path for Nodejs, and it's in my main PATH.
I see this message: Path to node interpreter is invalid Fix it
My specs is Windows 7 x64 Ultimate
WebStorm 10.0.1

**Comment by idok** [comment]
I believe in windows it should point to the rt.cmd file

**Comment by LOQUILLO** [comment]
Hi @idok not working.
