### ISSUE TITLE
Key is not defined

### ISSUE THREAD

**Issue by Anomen** [wix/react-templates#32]
Hi everyone!

I'm getting started with your useful templating engine.

I'm having this issue though, when I write this template:

```
<div id="LoginPage">
    <div rt-if="true == true">Hii</div>
</div>
```

I have this error:

```
ERROR in ./src/javascripts/pages/login/LoginPage.rt
Module build failed: TypeError: Cannot call method 'warn' of undefined
    at validate (/home/anomen/Desktop/circlad/front-end/node_modules/react-templates/src/reactTemplates.js:420:23)
    at Array.forEach (native)
    at validate (/home/anomen/Desktop/circlad/front-end/node_modules/react-templates/src/reactTemplates.js:423:23)
    at Array.forEach (native)
    at validate (/home/anomen/Desktop/circlad/front-end/node_modules/react-templates/src/reactTemplates.js:423:23)
    at Object.convertTemplateToReact (/home/anomen/Desktop/circlad/front-end/node_modules/react-templates/src/reactTemplates.js:438:5)
    at Object.module.exports (/home/anomen/Desktop/circlad/front-end/node_modules/react-templates-loader/index.js:5:24)
```

Opening this file at this line, I get:

```
        reportContext.warn('rt-if without a key', options.fileName, loc.pos.line, loc.pos.col, loc.start, loc.end);                                             
```

If I write:

```
<div id="LoginPage">
    <div key="heyy" rt-if="true == true">Hii</div>
</div>
```

It works well.

I keep reading the documentation, I don't see any mention of a property "key" (I may be wrong). Do I have to write a key in every single tag that uses rt-if?

Thanks!
Kevin

**Comment by EtaiG** [comment]
Hi Kevin,

This is due to a recent change in react-templates.
react-templates will now warn if you use rt-if without a key, since this is bad for performance.

I don't understand why it's exploding for you though - it seems you do not have the context module passed into the compile when you run it. 
How are you running react-templates?

Regarding the documentation- we will update it soon. Sorry for any inconvenience!

**Comment by Anomen** [comment]
I get this message when I run the command from my terminal:

![image](https://cloud.githubusercontent.com/assets/219680/7288655/23aab308-e933-11e4-8e99-7007cb067fb1.png)

When I run it with webpack, I get the other error.

![image](https://cloud.githubusercontent.com/assets/219680/7288665/4de49a08-e933-11e4-979c-3bb4aed01a3c.png)

I'm using the react-templates-loader (https://github.com/AlexanderPavlenko/react-templates-loader).

For the key, wouldn't it be possible to generate it when compiling the file automatically?

**Comment by heldr** [comment]
gulp plugin also breaks for the same reason

**Comment by idok** [comment]
fixed

**Comment by svicalifornia** [comment]
I'm also getting this warning on a brand new installation of react-templates:

      1:1  warning  rt-if without a key

My template:

    <div rt-if="1">
      Hello, world.
    </div>

What am I supposed to do here? Shouldn't the "key" be generated automatically if it's omitted?
