### ISSUE TITLE
Add the full MIT license to all the files

### ISSUE THREAD

**Issue by EtaiG** [wix/react-templates#4]
This is the standard and is probably a good idea

**Comment by gregwebs** [comment]
As a programmer I don't like this practice. It is not DRY and adds boilerplate that everyone has to scroll through. But I am no attorney.

**Comment by yordis** [comment]
:-1: The license is in the project so any legal problem is there. I don't want to see this practice, I am no attorney like @gregwebs said and that's extra bites in something that is 100% useless for the applications, that's just for legal stuff
