### ISSUE TITLE
lodash dependency

### ISSUE THREAD

**Issue by carlosdubus** [wix/react-templates#40]
Hi, I'm using react-templates in a project. All good so far :)

Question: what do you need lodash for? I see that you use _.map. What else? I'm asking because maybe you can add only the functions that you need instead of requiring the entire library. lodash increases js bundle size at least by 50k. Is not that much but is just a thought.

Thanks for this library!

**Comment by brodybits** [comment]
I put my answer in #28 which seems to overlap with your question.

**Comment by idok** [comment]
React templates assumes you have a _ library with some functions on it, you can see exactly with functions here:
https://github.com/wix/react-templates/blob/gh-pages/src/reactTemplates.js
at the beginning of the file.
It can be lodash, underscore or something else, it can also be a custom build of lodash if 50k is too much.
