### ISSUE TITLE
Location where project will be maintained

### ISSUE THREAD

**Issue by brodybits** [wix/react-templates#47]
This project does not seem to be maintained anymore. But there are users who are willing to maintain this project, see this comment for example: https://github.com/wix/react-templates/pull/43#issuecomment-125372680

Please specify where this project will be maintained. I am opening this issue to keep the discussion in one place.

**Comment by danyshaanan** [comment]
@brodybits @anchann:
As much as I would have wanted to spend all of my time in open source projects, I (and my fellow developers) still have to work on our core projects, the ones that this project serves.

I **am** committed to maintain this project, but please allow us more than a few days to find the time to properly address issues and PRs. In cases where it seems we have forgotten or missed something, feel free to mail me at the address that can be found on my Github profile, NPM profile, or homepage.

Thanks.

**Comment by brodybits** [comment]
Thanks @danyshaanan for your response, and I would like to thank you and the rest of the @wix organization for building and sharing this project! I do completely understand your time problem, and face it with my own projects.

I think it goes without saying that the community of users will only keep growing over time. Especially if someone gets a chance to try it with react-native.
