### ISSUE TITLE
Working with react-native?

### ISSUE THREAD

**Issue by brodybits** [wix/react-templates#48]
Examples would be cool!

**Comment by danyshaanan** [comment]
Hi @brodybits.
I do not know if it will, and I think that it is not something we will check anytime soon.
Would be cool if you could, though.
Thanks.

**Comment by nirnatan** [comment]
Hey @brodybits 
I'm currently working on adding react native support to react-templates. My guess is that it will be pushed in the next 1-2 weeks.

Thanks,
Nir

**Comment by brodybits** [comment]
Awesome, thanks!

**Comment by gino8080** [comment]
any update on this?

**Comment by nirnatan** [comment]
@brodybits This is ready since I closed the ticket. Sorry for not updating you that it was done.
You can find all the information in the [readme](https://github.com/wix/react-templates#use-react-templates-for-native-apps)
