### ISSUE TITLE
There's an improved version of this library available

### ISSUE THREAD

**Issue by anchann** [wix/react-templates#49]
I implemented some improvements to this library. Based on a chat in one of the issues, it seems that the authors here may be inactive or slow at dealing with PRs, so I branched the library here:

https://github.com/anchann/react-templates

Locally I'm using it with `npm link`. I figured we could publish parallel npm packages, perhaps `react-templates-improved`, but since I'm lazy, I won't proactively do so unless somebody asks me to.

**Comment by brodybits** [comment]
>
> https://github.com/anchann/react-templates
>
Nice work!


-- 
Sent from my mobile

**Comment by danyshaanan** [comment]
Hi @anchann!

I had just a minor part in the React Templates project, but I appreciate your contributions! The main maintainers of the project were too busy this week to see your work so far, but I'll make sure that they will look at this ASAP.

**Comment by anchann** [comment]
Hi @danyshaanan 

Thanks for the heads up. Stuff works locally for me, and folks interested in the new features can follow the same npm link approach, so none of this is blocking. That said, I haven't submitted PRs for the latest changes, in particular restoring rt-scope to its initial semantics, and implementing the new version as rt-inner-scope. The latest version is available here: https://github.com/anchann/react-templates

-a

**Comment by danyshaanan** [comment]
Hi @anchann.
We've dealt with some of the PRs, (+some other outstanding issues), and the rest are being looked at.
Is there anything else you've done that we should look at and you haven't shared with us here? PRs would be awesome, links to commits will be good as well...
D.

**Comment by anchann** [comment]
Hey @danyshaanan 

Everything I've done so far is sitting on https://github.com/anchann/react-templates, same place that I linked to above. I just looked at wix's gh-pages branch, and it looks like a bunch of the stuff I did is yet to be merged. Since you mention that this stuff is "being looked at", I suppose updating the PRs now would end up stepping on people's toes, so I'll just stand by for further instructions.

As far as additional work, I'm thinking of implementing `rt-if-not`, which would be far more readable than adding ! and wrapping stuff in parens unnecessarily.

Also was thinking of cleaning up the code a bit — you may have noticed how I scoped `rt-repeat-children`'s and `rt-inner-scope`'s data inside their own members on the `data` variable, while all the existing directives just dump stuff in there indiscriminately. Cleaning that up would make the codebase more welcoming to others, easier to read and maintain. With your test suite and my fairly large project now fully ported to react-templates, I feel reasonably confident to do refactoring without risking to break stuff and have it go unnoticed. This was my plan if you guys turned out to be truly unresponsive, and I were to play maintainer for a while. But now that that's not the case, I want to ask if such changes would be welcome or rejected before I attempt to make them.

-a
