### ISSUE TITLE
[Question] Usage with Facebook Flow

### ISSUE THREAD

**Issue by gregwebs** [wix/react-templates#53]
Does anyone have a workflow with react-templates that can preserve the type-checking properties one would get from JSX?

With JSX, template javascript can be type-checked by Flow because it resides next to the javascript using it. Generating code without type declarations into separate files or even just separate modules that rely on `this` is going to lose a lot of potential type-safety at the module boundary.

I can think of 2 approaches:

1) keep the template in the same file as the JS or otherwise directly include the resulting JS in that same file.
2) have react-template generate Flow type declarations that can be imported into the JS.

**Comment by gregwebs** [comment]
approach #1 of inlining the resulting js into the file with the react code works. This can be done with [gulp-include](https://www.npmjs.com/package/gulp-include), but I could not find an existing plugin for browserify, webpack, or babeljs

**Comment by rileylark** [comment]
@gregwebs how happy are you w/ this approach now?

**Comment by gregwebs** [comment]
works fine: things worked out much easier than I had expected.
