### ISSUE TITLE
Pass data to the template?

### ISSUE THREAD

**Issue by Anahkiasen** [wix/react-templates#54]
Is there no way to pass data to the template from the render method? Checked the docs and issues but couldn't find anything. Something like:

```js
import template from './MyComponent.rt';

export default class MyClass extends Component {
  render() {
    var someVariable = 'foobar';
    
    // How do I pass someVariable for it to be accessible?
    return template.apply(this);
  }
}
```

```html
<h1>{someVariable}</h1>
```

**Comment by ganimomer** [comment]
Hi,
The template from *.rt.js files is meant to be used as-is, i.e. `render: template`.
If you want to pass data to affect the rendering, you can assign it as a property of `this`.
```html
<h1>{this.someProperty}</h1>
```
However, I assume in the real world "someVariable" is calculated, either from `state`, `props`, or something else, in which case it might be better to insert the calculation to the template.
e.g.
```html
<h1>{this.state.foo + this.state.bar}</h1>
```
or, if it's more complicated, you could always extract it to a method of the class:
```js
import template from './MyComponent.rt';

export default class MyClass extends Component {
  render: template,
  fooBar() {
  // ... some complicated code
  }
}
```
```html
<h1>{this.fooBar()}</h1>
```
Does this help? If not, could you give a more specific use case?

**Comment by Anahkiasen** [comment]
Well I ended up going another way since but that would have worked indeed, yes. So good for me
