### ISSUE TITLE
Docs - not entirely clear how to compile or use with CommonJS?

### ISSUE THREAD

**Issue by ericclemmons** [wix/react-templates#6]
I see that there's a CommonJS example as the _output_ of the template, but when using tools like WebPack & `gulp-react`, I'm not sure how these templates would fit into my workflow.

Do I author a `myThing.jsx` and `myThing.react.html`?  How do I combine the two?

**Comment by idok** [comment]
Hi,
Working with React and CommonJS is simple:
Lets say you have a file myThing.rt, you will compile it to javascript using the CLI
```sh
$ rt myThing.rt -m commonjs
```
This will result in myThing.rt.js, that you can require from myThing.js.
I recommend installing the yeoman generator https://github.com/wix/generator-react-templates
You can run it and select a commonjs project and see a working example.
Hope this helps.

**Comment by ericclemmons** [comment]
What's the best way to use it via the API, not the CLI?  Since I'm using Gulp & Webpack, I'll need some direct hook with Javascript...

Thanks!

**Comment by idok** [comment]
You can also use it via grunt plugin or intellij plugin.
here's an example of API usage
https://github.com/wix/grunt-react-templates/blob/master/tasks/react-templates.js

**Comment by ericclemmons** [comment]
That's what I want.  Thanks!
