### ISSUE TITLE
Props that are React Elements are not supported

### ISSUE THREAD

**Issue by Nargler** [wix/react-templates#64]
I'm using material-ui in a project and was hoping to use react-templates as a tidy way to remove the html content from the jsx.

Problem encountered though in using the ListItem component, it has some optional props that expect to be passed React Elements.

So in jsx you might have

`var mui = require('material-ui');
var FileFolder = require('material-ui/lib/svg-icons/file/folder');`

.... in render

`<mui.ListItem primaryText="Example item" leftIcon={<FileFolder />} />`

In my rt file I I can rt-require the material component straight forward enough.
On compilation though you'll get a parse error

Failed to parse text `'{<FileFolder' while parsing file: <file path>`

I presume because rt is treating the `{}` markup as signifying javascript snippet?

I guess such nesting is outside of react-templates scope currently?

**Comment by idok** [comment]
Have you tried something like this:
```html
<rt-require dependency="./FileFolder" as="FileFolder"/>
<ListItem leftIcon="{React.createElement(FileFolder)}"></ListItem>
```

**Comment by Nargler** [comment]
That works in the simple case thanks!  If one wishes to set the component's props then one hits the same issue again since that would typically be using an object literal like so...

`React.createElement(FileFolder, {className: "myClassName"})`

**Comment by Nargler** [comment]
Came back to this for anyone interested, workaround was to create helper functions in the parent class. These can either create the desired element in whole within the jsx (as below) or could be used factory like to return the appropriate object literal for use to specify props.

in jsx file
```
...
_getIcon: function(icon) {
    if (icon == 'FileFolder') {
       return (<FileFolder className="folderclass"/>);
    }
    ...
},
...
```
in rt file
```
<ListItem leftIcon="{this._getIcon('FileFolder')}"></ListItem>
```
