### ISSUE TITLE
Jest integration

### ISSUE THREAD

**Issue by Malo87** [wix/react-templates#65]
Hi, I've just introduced react-templates and I'm having trouble to preprocess the .rt files

 tracker@1.0.0 test /home/****
> jest

Using Jest CLI v0.5.2
 FAIL  __tests__/tracker-test.js (0.862s)
● Tracker › it Verify that the state contains the given steps
  - SyntaxError: /home/***/tracker.js: /home/**/tracker.rt: Unexpected token <

It's blowing up because the .rt file is not compiled.

Jest is configured as follow:
https://facebook.github.io/jest/docs/tutorial-react.html#setup

But I'm pretty sure that I need to write a custom preprocessor that invokes react-template AND deamdify (or let react-template to compile directly to commonjs).

Any suggestion?

**Comment by idok** [comment]
Hi,
I have no experience with Jest, but I guess that if you should use the *.rt.js files that are the output of react-templates instead of the *.rt file.
*.rt.js files are just javascript and should work.
Hope that helps

**Comment by Malo87** [comment]
Ok, after a bit of pain I manage to get a preprocessor.js for Jest. Can be definitely improved but works for me http://pastebin.com/m029Nbyn

Just a few gotcha:
```
var reactTemplates = require("react-templates");
reactTemplates.convertTemplateToReact(src, {modules: "commonjs"});
```
is used to convert the file.rt

You need to tell jest that .rt files are good for preprocessing and, I think, not to mock *.rt files in your path (the templates)

```
"jest": {
    "unmockedModulePathPatterns": ["<rootDir>/node_modules/react", 
 "<rootDir>/node_modules/react-native", "./*.rt"],
    "scriptPreprocessor": "./preprocessor.js",
    "testFileExtensions": [
      "rt",
      "js"
    ],
    "moduleFileExtensions": [
      "js",
      "rt"
    ]
  },
```

and when you run the test, remember to remove the automock when you require the component that is rendered (otherwise things like rt-repeat doesn't work)

  ```
   //   ./__tests__/MyModule-test.js
   jest.autoMockOff();
    var MyModuleWithTemplates = require('../myModule.js');
    jest.autoMockOn();
```

**Comment by delijah** [comment]
I was able to run jest tests with react-templates by using the following preprocessor.js:

```
var babel = require('babel-core');
var rt = require('react-templates');

module.exports = {
    process: function(src, path) {
        if (path.match(/\.js$/)) {
            return babel.transform(src, { extends: './.babelrc' }).code;
        } else if (path.match(/\.rt$/)) {
            return rt.convertTemplateToReact(src, { modules: 'commonjs' });
        }

        return src;
    }
};
```
