### ISSUE TITLE
parse component 's props error

### ISSUE THREAD

**Issue by skyblue** [wix/react-templates#67]
I use a component in a .rt file , like:
```html
<Table dataSource={this.state.fakeData} columns={this.state.columns}/>
```
then `columns`  be parsed to  string type, but it's an array

but.
```html
<Table dataSource={this.state.fakeData} columns={this.state.columns} />
```
it worked~
the only  difference is one space

**Comment by idok** [comment]
This is due to a limitation of the parser we use, we recommend using quotes around attributes value to prevent it
```html
<Table dataSource="{this.state.fakeData}" columns="{this.state.columns}"/>
```
