### ISSUE TITLE
Route.Link

### ISSUE THREAD

**Issue by rollrodrig** [wix/react-templates#71]
How can i get this
`
var Router 		= 	require('react-router');
var Link		=	Router.Link;
`
Whit this
`
<rt-require dependency="react-router" as="ReactRouter"/>
<rt-require dependency={ReactRouter.Link} as="Link"/>
`

**Comment by idok** [comment]
Try this:
```
<rt-require dependency="react-router" as="ReactRouter"/> 
<div rt-scope="Link as ReactRouter.Link"></div>
```

**Comment by duvanskiy** [comment]
<rt-require dependency="react-router/lib/Link" as="Link"/>

**Comment by jlpellicer** [comment]
With react-templates versino 0.5.2 and react-router version 2.4.1:
<rt-import name="default" as="Link" from="react-router" />
<Link to="countries">Countries</Link>
