### ISSUE TITLE
Deprecation warning on installation

### ISSUE THREAD

**Issue by svicalifornia** [wix/react-templates#72]
Installed react-templates today:

    $ npm install react-templates -g
    npm WARN deprecated esprima-harmony@7001.1.0-dev-harmony-fb: use esprima-fb instead

Maybe your package.json should be updated?

**Comment by 7app** [comment]
I've had the same problem ...
`sudo npm install react-templates -g`
`npm WARN deprecated esprima-harmony@7001.1.0-dev-harmony-fb: use esprima-fb instead
npm WARN install:esprima-harmony@7001.1.0-dev-harmony-fb invalid version: 7001.0001.0000-dev-harmony-fb`
