### ISSUE TITLE
Is there an option to use react-templates with stateless components?

### ISSUE THREAD

**Issue by someone235** [wix/react-templates#75]

**Comment by osasseville** [comment]
Like this?

https://facebook.github.io/react/blog/2015/09/10/react-v0.14-rc1.html#stateless-function-components

**Comment by someone235** [comment]
Yes

**Comment by osasseville** [comment]
I was actually looking for it when I saw this post. This would be a pretty cool feature.

**Comment by nippur72** [comment]
If `rt` has to produce stateless components, then we must first define how to differentiate it from normal components.

There could be an "automatic" implicit way like: if there's no `this` within the JavaScript then it is a stateless function. But I would prefer a more explicit way. 

I propose adding an `rt-stateless` attribute on the root element, e.g.:

```HTML
<div rt-stateless>
   Hello {props.person}
</div>
```
Do you have other ideas?

**Comment by nippur72** [comment]
I already have a PR waiting to be pushed :-)

**Comment by nippur72** [comment]
See #129 for my attempt to solve this.

Instead of using an `rt-stateless` attribute I've opted for self closing `<rt-stateless>` component.

Tell me if you like it or want something to be changed.

**Comment by nippur72** [comment]
Oops, I think we pushed almost at the same time!
