### ISSUE TITLE
compiled rt not using React.DOM

### ISSUE THREAD

**Issue by engenb** [wix/react-templates#76]
react: 0.14.3
react-dom: 0.14.3
react-templates: 0.3.2
react-templates-loader: 0.2.0

snippet from my webpack.config.js:
```
module: {
  loaders: [
    { test: /\.rt/, loader: 'react-templates-loader' }
  ]
}
```
The examples in your README.md show the expected compiled template using ```var React = require('react')``` and ```React.DOM``` for creating elements.

In my compiled templates (and on http://wix.github.io/react-templates/), react is being pulled in via ```require('react/addons')``` which is now deprecated.
```
Warning: require('react/addons') is deprecated. Access using require('react-addons-{addon}') instead.
```
I think, ideally, React would be required in via ```require('react')``` or ```require('react-dom')``` as illustrated in your README.md - is this an issue with the webpack loader I'm using?  What is the preferred approach for compiling react templates?  Or, is there something I'm missing?

Thanks!

**Comment by idok** [comment]
update react-templates-loader to the latest version and add to the webpack.config.js the target version like the following example:
```js
{test: /\.rt/, loaders: ['react-templates-loader?targetVersion=0.14.0'], include: path.join(__dirname, 'src')}
```

**Comment by engenb** [comment]
after doing that, I still see react being required in via 'react/addons' and is now throwing an error.  appears to fail the LinkedStateMixin in ReactWithAddons.js
