### ISSUE TITLE
Warning: require('react/addons') is deprecated. Access using require('react-addons-{addon}') instead.

### ISSUE THREAD

**Issue by Thisman** [wix/react-templates#77]

**Comment by opichals** [comment]
This can be solved by using the targetVersion=0.14.0 option.

Perhaps the ReactDOMSupport.default should be changed to 0.14.0 to avoid using the deprecated react/addons...

**Comment by EvAlex** [comment]
What is targetVersion and where do I find it? Same issue.

**Comment by EvAlex** [comment]
Found it. It is an option in opions argument in
```js
require('react-templates/src/reactTemplates').convertTemplateToReact(source, options);
```

**Comment by steezeburger** [comment]
Where is this option set? I have to overwrite the library's config?

**Comment by steezeburger** [comment]
Where is this option set? I'm using grunt-react-templates and trying to set it in the options object in the grunt init config, but I don't think this is the place to put it. Any ideas?

**Comment by ransomw** [comment]
i was trying out the react-templatify browserify transform and ran across this issue.  for the moment, writing

```javascript
  var updated_react_templatify = function (file, options) {
    var opts = options || {};
    opts.targetVersion= '0.14.0';
    return react_templatify(file, opts);
  };
```

and then using `updated_react_templatify` [just as i'd use `react_templatify`](https://github.com/ransomw/movie-time/blob/b9ed795d09de53948f267691f4eeddf9b023f603/core/client/index.js#L28) (and `untabify`ing that file, d'oh!) prevents the error.

note that the version string in the `updated_react_templatify` version is not the same minor version as the react npm package, and changing `'0.14.0'` to match the `"0.14.7"` in `package.json` creates errors.  this is not a practical issue for my use case.
