### ISSUE TITLE
How to use react-templates in a simple web application without being in a node environment?

### ISSUE THREAD

**Issue by topgun743** [wix/react-templates#79]
I want to use react-templates in my Asp.Net based website. I have npm installed on my system.
I have react-addons added to my page header.
But I donot know how to generate a react-templates.js file that I can then add to my page's header section also and so use it along with react.
Can someone please guide?

**Comment by nippur72** [comment]
You don't need to link a `react-templates.js` file, only the standard React is needed. 

The only thing you need to link are the compiled template files (*.rt.js). 

So:
1) create template files (*.rt)
2) compile them from command line (`rt *.rt` )
3) ship the `*.rt.js` files and use them in your React code
