### ISSUE TITLE
Support custom delimiters

### ISSUE THREAD

**Issue by nippur72** [wix/react-templates#81]
It would be nice if expression delimiters `{` and `}` could be customized (e.g. setting them to `{{ }}` or `${ }` etc.)

**Comment by nippur72** [comment]
I made a PR #84 for this issue.

**Comment by ganimomer** [comment]
@avi commented on this in #84.
We waited to get some extra feedback and received none for quite a while, so we guess this feature is not supported.

We'll reopen this if this changes.
