### ISSUE TITLE
Unable to build under Windows

### ISSUE THREAD

**Issue by nippur72** [wix/react-templates#82]
I can't build it in Windows (7 x64): after cloning it and `npm i`, I get the following error when I try to `grunt all` or `grunt test`:
```
Running "tape:files" (tape) task
Fatal error: spawn C:\react-templates\node_modules\grunt-tape\node_modules\tape
\bin\tape ENOENT
```

Task `default` and `pgall` do work anyway. Any idea? I would like to contrib, but it's hard it I can't run tests :-)

**Comment by idok** [comment]
please try running
```bash
npm run all
```

**Comment by nippur72** [comment]
Ok, with `npm run all` tape does work and the build step is completed correctly.

But there seems to be another issue: I've just cloned the new `0.4.0/gh-pages` and `grunt pgall` that previously worked now throws this:
```
Running "uglify:my_target" (uglify) task
JS_Parse_Error {
  message: 'Unexpected token: name (RTCodeError)',
  filename: 'rt-main.browser.js',
  line: 57572,
  col: 6,
  pos: 1936103, ... }
>> Uglifying source playground/dist/rt-main.browser.js failed.
```

Looking at `rt-main.browser.js` at the indicated line revealed some ES6 "class" code.

Thank you for your precious help, I look forward to collaborate with this great project (I have some nice ideas).

**Comment by idok** [comment]
I will check it, however, that grunt task is for the playground web page and is not required for react-templates contribution so it should not block you.

**Comment by nippur72** [comment]
Regarding `grunt pgall`, the browserify script builds reading from `src\RTCodeError.js` which is now ES6 and thus can't run on the browser. 

I think a `babel --presets es2015` is required between the `browserify` and `uglify`.

**Comment by nippur72** [comment]
I'm closing this and opening a specific issue for the playground one.
