### ISSUE TITLE
Introduce a <template> or <virtual> element that is discarded and only serves if/repeat logic

### ISSUE THREAD

**Issue by antitoxic** [wix/react-templates#85]
Riotjs has [`<virtual>`](http://riotjs.com/guide/#the-virtual-tag) element and Polymer has [`<template>`](https://www.polymer-project.org/1.0/docs/devguide/templates.html#dom-if). 

Both are elements that are not included in the final DOM rendering. They are just DOM placeholders for instructions such as `if` or `repeat`.

I have scenario where I have conditional logic but I don't need a wrapper element. 

It's also related to what @anchann has implemented with `repeat-children` but is more generic and will serve conditionals as well and any other operation if needed.

**Comment by nippur72** [comment]
Eh!, I was about to open the same issue!

I don't like the `rt-repeat-children` solution as it's a bit hard to read and also it's specific to `repeat`. 

I think we can handle it more elegantly with a `<virtual>` tag just like in RiotJs. 

I was experimenting in the playground with a `vitual` component that returns `{this.props.children}`, and it kinda works, but of course it's best we handle it directly without the extra element.

**Comment by nippur72** [comment]
I'm working on a PR for this.

Before I write tests and docs, can you please tell me if we want to adopt `<rt-virtual>` instead of `<virtual>`?

**Comment by nippur72** [comment]
See #86 (I changed to `rt-virtual` to be consistent with `rt-template`)
