### ISSUE TITLE
minimize lodash size

### ISSUE THREAD

**Issue by nippur72** [wix/react-templates#87]
(This is related to #40 and #28)

In order to minimize the impact of `lodash` over the total app size, I've traced back which methods are strictly necessary to work react-templates:
```js
module.exports = {
   map:      require("lodash/collection/map"),
   assign:   require("lodash/object/assign"),
   defaults: require("lodash/object/defaults"),
   keys:     require("lodash/object/keys"),
   pick:     require("lodash/object/pick"),
   identity: require("lodash/utility/identity")
}
```
(that produces a minified bundle of approx 30k versus the 104k of the whole library)

I was thinking of creating a separate npm package (like `rt-lodash`) so that we can require it in place of the original `lodash`. What do you think? is there a simpler alternative?

**Comment by nippur72** [comment]
Closing this as a custom `loadsh` build can be done simply by installing lodash's cli utility.

**Comment by rileylnapier** [comment]
hi, do you have example lodash-cli that worked for you?

**Comment by idok** [comment]
you can use webpack and the code above to create a custom build
