### ISSUE TITLE
How do I pass html tags and html entity to template through  this.state without escaping !!!

### ISSUE THREAD

**Issue by askuiop** [wix/react-templates#92]
Here is the template code:
<p>&lt;div class=&quot;blog-post&quot; rt-repeat=&quot;item in this.state.data&quot;&gt;</p><p>
    &lt;h2 class=&quot;blog-post-title&quot;&gt;{item.title}&lt;/h2&gt;</p><p>
    &lt;p &gt;{item.summary}&lt;/p&gt;</p><p>
    &lt;p &gt;{item.content}&lt;/p&gt;</p><p>
 &lt;/div&gt;</p>

<p>The {item.content} has html tags or html entity like: &lt;p&gt;....&amp;nbsp;....&lt;/p&gt;  etc.
</p><p>what should I do to let it display normally ???</p>

**Comment by nippur72** [comment]
use `dangerouslySetInnerHTML` as in:
```HTML
<div>
  <p dangerouslySetInnerHTML="{{__html: '<div>your content here</div>'}}"> 
  </p>
</div>
```
of course you should be aware that is a discouraged practice.

**Comment by askuiop** [comment]
I knew the "dangerouslySetInnerHTML" , but I don't know the usage. The office docs are so simple, especially the RT's .
I tried several times,and found the correct format:
<p dangerouslySetInnerHTML="{{__html: item.summary}}"></p>
or with html tags :
<p dangerouslySetInnerHTML="{{__html: '<div>'+item.summary+'</div>'}}"></p>
It feels strange....
thanks a lot!
